### ISSUE TITLE
User-created DomError component present in the DOM tree

### ISSUE THREAD

**Issue by barucAlmaguer** [unboundedsystems/adapt#6]
CURRENT BEHAVIOUR:

I'm having troubles running the Hello world example for Adapt, I keep getting an error when running:

`adapt run --deployID movieapp`

The full error log in the console is this:
```
adapt run --deployID movieapp       
Adapt by Unbounded Systems [CLI v0.1.0]

  ✔ Installing node modules
  ✔ Validating project
  ❯ Creating new project deployment
    ✔ Compiling project
    ✖ Building new DOM
      → Error building Adapt project
      Loading previous DOM
      Observing environment
      Deploying

8 warnings encountered during deploy:
[DOM build] : User-created DomError component present in the DOM tree
[DOM build] : Component Container cannot be built with current props: Component construction failed: Unable to find constructor with correct name. Outer constructor is: cloud.Container
[DOM build] : User-created DomError component present in the DOM tree
[DOM build] : Component Container cannot be built with current props: Component construction failed: Unable to find constructor with correct name. Outer constructor is: cloud.Container
[DOM build] : User-created DomError component present in the DOM tree
[DOM build] : Component Container cannot be built with current props: Component construction failed: Unable to find constructor with correct name. Outer constructor is: cloud.Container
[DOM build] : User-created DomError component present in the DOM tree
[DOM build] : Component Container cannot be built with current props: Component construction failed: Unable to find constructor with correct name. Outer constructor is: cloud.Container

 ›   Error: This project cannot be deployed.
 ›   1 error encountered during deploy:
 ›   [deploy:run] : Error creating deployment: Error building Adapt project
 ›
 ›   Deployment not created due to errors
```

EXPECTED BEHAVIOUR:

Example project builds and runs successfully

PROJECT:

https://github.com/barucAlmaguer/adapt-hello-world

**Comment by mterrel** [comment]
Hi @barucAlmaguer, sorry you're having an issue! It looks like this may be due to a bug in Adapt when its run on later versions of Node.

Could you please send the output of `adapt version` so I can verify that the fix will work for you?

I'm working on a fix now. But until the fix is available, you should be able to run Adapt with Node version 10. If you aren't already using `nvm`, it's a super easy way to switch between Node versions. Here's [info on installing Node 10 with nvm](https://adaptjs.org/docs/user/install/requirements) if you'd like to give that a try.

**Comment by mterrel** [comment]
@barucAlmaguer This should be resolved in v0.2.0-next.3, which was just published. Would you mind checking if the update fixes your issue? To install the `next` version:

```
npm install -g @adpt/cli@next
```

I'm going to go ahead and close the issue, but if the newer version doesn't solve your issue, I'll re-open it.

**Comment by garethbrickman** [comment]
I am still having the same issue even after updating:

`deploy% adapt version
@adpt/cli/0.2.0-next.3 darwin-x64 node-v13.8.0`

`deploy% adapt run --deployID movieapp
Adapt by Unbounded Systems [CLI v0.2.0-next.3]

  ✔ Installing node modules
  ✔ Validating project
  ❯ Creating new project deployment
    ✔ Compiling project
    ✖ Building new DOM
      → Error building Adapt project
      Loading previous DOM
      Observing environment
      Deploying

8 warnings encountered during deploy:
[DOM build] : User-created DomError component present in the DOM tree
[DOM build] : Component Container cannot be built with current props: Component construction failed: Unable to find constructor with correct name. Outer constructor is: cloud.Container
[DOM build] : User-created DomError component present in the DOM tree
[DOM build] : Component Container cannot be built with current props: Component construction failed: Unable to find constructor with correct name. Outer constructor is: cloud.Container
[DOM build] : User-created DomError component present in the DOM tree
[DOM build] : Component Container cannot be built with current props: Component construction failed: Unable to find constructor with correct name. Outer constructor is: cloud.Container
[DOM build] : User-created DomError component present in the DOM tree
[DOM build] : Component Container cannot be built with current props: Component construction failed: Unable to find constructor with correct name. Outer constructor is: cloud.Container

 ›   Error: This project cannot be deployed.
 ›   1 error encountered during deploy:
 ›   [deploy:run] : Error creating deployment: Error building
 ›   Adapt project
 ›
 ›   Deployment not created due to errors`
